# Generated by Django 4.1.7 on 2024-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Objeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cont", models.PositiveIntegerField(default=0)),
                (
                    "nome",
                    models.CharField(
                        blank=True, default="None", max_length=55, null=True
                    ),
                ),
                (
                    "src",
                    models.CharField(
                        blank=True, default="None", max_length=55, null=True
                    ),
                ),
            ],
        ),
    ]
